repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: "v0.3.0"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  # python static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
      - id: mypy
        args:
          - --disallow-untyped-defs
          - --disallow-incomplete-defs
          - --check-untyped-defs
          - --no-implicit-optional
          - --ignore-missing-imports
          - --follow-imports=silent
